// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/todo_features_1/data/models/todo_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(2, 7622225495429988703),
      name: 'TodoEntityModel',
      lastPropertyId: const IdUid(5, 5185568501039519135),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7655017306146496126),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(4, 1218091181965698679),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 5185568501039519135),
            name: 'isChecked',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 7622225495429988703),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [4823853276646981873],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        9197142743828528127,
        203873650708711258,
        515658982322732346,
        7790465159099872257
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TodoEntityModel: EntityDefinition<TodoEntityModel>(
        model: _entities[0],
        toOneRelations: (TodoEntityModel object) => [],
        toManyRelations: (TodoEntityModel object) => {},
        getId: (TodoEntityModel object) => object.id,
        setId: (TodoEntityModel object, int id) {
          object.id = id;
        },
        objectToFB: (TodoEntityModel object, fb.Builder fbb) {
          final titleOffset =
              object.title == null ? null : fbb.writeString(object.title!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(3, titleOffset);
          fbb.addBool(4, object.isChecked);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final isCheckedParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 12);
          final object = TodoEntityModel(
              id: idParam, title: titleParam, isChecked: isCheckedParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TodoEntityModel] entity fields to define ObjectBox queries.
class TodoEntityModel_ {
  /// see [TodoEntityModel.id]
  static final id =
      QueryIntegerProperty<TodoEntityModel>(_entities[0].properties[0]);

  /// see [TodoEntityModel.title]
  static final title =
      QueryStringProperty<TodoEntityModel>(_entities[0].properties[1]);

  /// see [TodoEntityModel.isChecked]
  static final isChecked =
      QueryBooleanProperty<TodoEntityModel>(_entities[0].properties[2]);
}
